### PR TITLE
Adding RVM listing for Rubinius

### PR DESCRIPTION
**Pull request by bjfish**
Hello, I would like to add Rubinius to your RVM list in your travis build to test this gem for compatibility.  Thank you.

### CODE REVIEW

**Comment by hsbt** [comment]
I can't merge this pull request. Because test is fail

**Comment by bjfish** [comment]
Hi @hsbt , I've updated the PR to allow Rubinius as an Allowed Failure to not fail the build if the Rubinius job fails.

**Comment by hsbt** [comment]
@tenderlove Do you have any plan of rubinius support?

**Comment by tenderlove** [comment]
It's OK if we have it in the allow failures section.

**Pull request merged**
