### PR TITLE
Add optional fallback return value parameter

### PR DESCRIPTION
**Pull request by tuexss**
As suggested in https://github.com/tenderlove/psych/issues/149

### CODE REVIEW

**Comment by tenderlove** [comment]
LGTM. You mentioned in #149 that we should be returning `nil` by default. I think we should, but I'm unsure if I could change this return value in a bugfix release.  I guess `nil` is still falsey, and the behavior isn't documented, so I'm not sure.

**Comment by tuexss** [comment]
Yes, I agree. Adding a feature is one thing, changing current behavior a different one. Maybe it should fail with a proper exception.

Do you have any idea what I can do about appveyor failing?

**Comment by sandstrom** [comment]
I just hit this. Getting `nil` in return is what I'd expect, and since both `false` and `nil` are falsy I wouldn't be to worried about changing in a bugfix release.

**Comment by sandstrom** [comment]
Nice! ⛵

**Pull request merged**
